### ISSUE TITLE
How to use on AppCode JetBrains IDE

### ISSUE THREAD

**Issue by evyasafhouzz** [divadretlaw/urban#2]
After putting the urban.icls file under colors folder I can't find the place to modify the theme from the AppCode IDE.

Mac 10.14.4

**Comment by divadretlaw** [comment]
Put the `urban.icls` file into `~/Library/Preferences/AppCode2019.1/colors/`.

Restart AppCode

Now select the color scheme in "Preferences > Editor > Color Scheme"

Tested with macOS 10.14.4 and AppCode 2019.1

**Comment by evyasafhouzz** [comment]
Great, it works like a charm!
I think best is if you will add it to the instructions.

tnx
